---
title: "Why Blog, Why Today?"
author: "James Clawson"
date: "2019-01-28"
output: 
  tufte::tufte_html: default
  blogdown::html_page: default
excerpt: "This is the perfect time not to start a blog, yet here I am. It feels necessary to start with a preface, with something to explain why I’m doing this, why I’m doing it now, and what I hope will result. In the spirit of the web, here’s a listicle of the Top Six Reasons I’ve Begun a Blog. (You won’t believe number three!)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

It’s 2019: The pond and the fry-up both feature bigger fish. This is the perfect time not to start a blog, yet here I am, even going so far as to address an empty venue as if there were already an audience. I could be wrong—as a novitiate, I probably am wrong—but it feels necessary to start with a preface, with something to explain why I’m doing this, why I’m doing it now, and what I hope will result. In the spirit of the web, here’s a listicle of the Top Six Reasons I’ve Begun a Blog.

## 1. I’ve learned from blogs; it feels right to share what I’ve learned.
I trained first in literature. Throughout school, college, and grad school, although I was always interested in computers and in learning to convince them to do the kinds of things that they wouldn’t do without convincing, this pursuit was never more than a side interest. This pastime has increasingly shifted from the weekends to the everyday, as I’ve been using computational methods to augment my studies in literature. As a once- and still-newcomer to many of these approaches, I’ve had to piece together from whatever sources I could find. Blogs have often been the best place to learn some of the best practices.  Just as I’ve used blogs to find and develop methods that have been useful for my purposes along the way, it feels right to share things in turn using the same medium.

## 2. Incremental lessons may best be shared in an incremental genre.
Can I simplify the attendance-taking process for classes I teach? How do I programmatically categorize hues like crimson and aquamarine into general color categories like red and blue? What’s the best way to recognize clusters of one kind of feature in a large corpus of material? What’s the best way to *get* a large corpus of material? These are problems that took me time to solve, often in service of some larger goal that was my main focus. A blog feels good for writing up these smaller solutions while also keeping the writing decks clear and ready for the larger projects they serve.

## 3. I am forgetful. 
The timeline of process with digital work is longer than an elephant’s trunk, and my memory is shorter. While archival work and other literary research already necessarily involve documenting as part of the process, computational work, writing code for a project from scratch, often begins with exploratory processes that get abandoned, refined, or replaced. Only when they’re remembered do decisions made at this stage reveal anything about a project. 

Put another way, analyzing a text is like cutting up a picture into a puzzle and then assembling these puzzle pieces in some new way to form an entirely new picture, but analyzing a corpus of texts is like cutting up hundreds of pictures to form thousands of puzzle pieces and reshaping them into many numbers of new pictures. I need a strategy for keeping track as I go, and I’m hopeful this blog will help me keep track.

## 4. Writing is a process of discovery; clarifying is a process of understanding.
If I’m going to tell my students that “writing isn’t just the *communication* of ideas; it’s also a *process for learning to understand* ideas,” then I need to understand it as a truth in my own work, too. This blog is dogfood. And that’s a good thing.

## 5. Coding more has meant writing less often.
The shift toward digital in my research has included a shift away from writing during the process, as I was more apt to do with my literary work. I want to change that, writing more while I go, and a blog makes sense.

## 6. Communication defies loneliness.
The first few months of research for my dissertation were very lonely.^[My mentioning it fifteen years later shows that I’m still mildly traumatized.] In time, I learned techniques to combat loneliness without sacrificing productivity. I’m far less lonely today in my work today, but I still like the idea of joining conversations of process and progress—conversations that might in 2019 exist more in theory than in actuality, living as we are in the times of numerous publications sounding blogging's death knell.^[For more on how passé it is for me to begin blogging now, see [[1](https://www.theatlantic.com/technology/archive/2015/02/what-blogging-has-become/386201/)], [[2](https://www.theguardian.com/media-network/media-network-blog/2014/jul/16/blogging-dead-bloggers-digital-content)], [[3](https://www.bbc.com/news/world-asia-25775191)], [[4](https://www.nytimes.com/2011/02/21/technology/internet/21blog.html)], or [[5](https://eric.ed.gov/?id=ED525056)].] But I’ve never been trendy. And since I don’t work in a vacuum, I need to do my part in contributing hot air to the atmosphere.

##  

## Bon appétit!
I have no assurances it’ll work. This first post is just a recipe for pudding, the proof of which will come only with sufficient time to revisit my expectations and judge the dish as successful or failed. I have a banquet of posts in mind, however, and I need only to balance my front and back burners, only to keep the kitchen hot.
